[package]
name = "github-advent-calendar"
version = "0.1.0"
authors = ["raedion <u548026g@ecs.osaka-u.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
github-rs = "0.7.0"
serde_json = "1.0.0"